config/routes.rb
CrimeApp::Application.routes.draw do
  
  get "/" => "Crimes#front_page", :as => :front_page
  get "/crimes/front_page" => "Crimes#front_page", :as => :front_page
  
  get "/crimes/show_threat" => "Crimes#show_threat", :as => :show_threat

  resources :crimes  
  
  
end

app/models/crime.rb
class Crime < ActiveRecord::Base
  attr_accessible :block, :crime_type, :date, :description, :latitude, :location_type, :longitude, :address
  
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  # GET /crimes
  # GET /crimes.json
  def index
    @crimes = Crime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crimes }
    end
    
  end

  # GET /crimes/1
  # GET /crimes/1.json
  def show
    
    @lat = cookies[:lat]
    @long = cookies[:long]
    
    @crime = Crime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/new
  # GET /crimes/new.json
  def new
    @crime = Crime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/1/edit
  def edit
    @crime = Crime.find(params[:id])
  end

  # POST /crimes
  # POST /crimes.json
  def create
    @crime = Crime.new(params[:crime])

    respond_to do |format|
      if @crime.save
        format.html { redirect_to @crime, notice: 'Crime was successfully created.' }
        format.json { render json: @crime, status: :created, location: @crime }
      else
        format.html { render action: "new" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crimes/1
  # PUT /crimes/1.json
  def update
    @crime = Crime.find(params[:id])

    respond_to do |format|
      if @crime.update_attributes(params[:crime])
        format.html { redirect_to @crime, notice: 'Crime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1
  # DELETE /crimes/1.json
  def destroy
    @crime = Crime.find(params[:id])
    @crime.destroy

    respond_to do |format|
      format.html { redirect_to crimes_url }
      format.json { head :no_content }
    end
  end
  
  def show_threat
    
    if params[:radius].to_i <= 2
      @radius = params[:radius]
    else
      redirect_to front_page_path, :flash => { :error => "Radius cannot be greater than 2 miles" }
      return
    end
    
    
    @lat = cookies[:lat].to_f
    @long = cookies[:long].to_f
    
    @crimes = Crime.near("#{@lat},#{@long}",@radius,:order => :distance)
  
  end
  
  def front_page
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/crimes/_form.html.erb
<%= form_for(@crime) do |f| %>
  <% if @crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crime.errors.count, "error") %> prohibited this crime from being saved:</h2>

      <ul>
      <% @crime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :block %><br />
    <%= f.text_field :block %>
  </div>
  <div class="field">
    <%= f.label :crime_type %><br />
    <%= f.text_field :crime_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location_type %><br />
    <%= f.text_field :location_type %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing crime</h1>

<%= render 'form' %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/front_page.html.erb
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD-CoFQIz_EPUpGuYeCLaX0zzCv9o4bXf8&sensor=false">
    </script>

            <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>

    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD-CoFQIz_EPUpGuYeCLaX0zzCv9o4bXf8&sensor=false">
    </script>

<script type="text/javascript">


var directionsDisplay;
var directionsService = new google.maps.DirectionsService();
var map;
var start = new google.maps.LatLng(41.86593, -87.64686);
var end = new google.maps.LatLng(41.88897, -87.63392);
var isHeatmap = true;


function initialize() {
        directionsDisplay = new google.maps.DirectionsRenderer();
        var chicago = new google.maps.LatLng(41.850033, -87.6500523);
        var mapOptions = {
                zoom:10,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                center: chicago
        }

        map = new
google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        directionsDisplay.setMap(map);



        var layer = new google.maps.FusionTablesLayer({
                query: {
                        select: 'location',
                        from: '1KlcxGqe8GBKtCaeA0Pvjbd701kygcwjoOsn14fQ'
                },
heatmap: {
                        enabled: isHeatmap
                }
        })

        layer.setMap(map);

}

function calcRoute() {
        var selectedMode = document.getElementById("mode").value;

        var request = {
                origin: start,
                destination: end,
                travelMode: google.maps.TravelMode[selectedMode]
        }

        directionsService.route(request, function(response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                        directionsDisplay.setDirections(response);
                }
        })


}


$(function(){
        initialize();
        calcRoute();


        $("#mode").change(function(){
                calcRoute();
        })



        $("#isHeatmap").change(function() {
                        isHeatmap = $("#isHeatmap").is(":checked");
                        initialize();
                        calcRoute();
        })


        $("#isHeatmap").is(":checked")


        $("#update-route").click(function(event){
                        event.preventDefault();

                        var from = $("#from").val();
                        var to = $("#to").val();

                        alert(from);
                        alert(to);

                        start = from;
                        end = to;

                        calcRoute();
        });

})
    </script>

	<script>
	  getGeoLocation();
	</script>

	<head>
		<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

	</head>
<h1 class="hood">Am I in the Hood?</h1>
<div class="container2">
<p id="error"><%= flash[:error] %></p>

<%= form_tag("/crimes/show_threat", :method => 'get') do %>
<%= label_tag(:radius, "Search Radius:") %>
<select name = "radius">
  <option value="0.1">0.1 miles</option>
  <option value="0.2">0.2 miles</option>
  <option value="0.3">0.3 miles</option>
  <option value="0.4">0.4 miles</option>
  <option value="0.5">0.5 miles</option>
  <option value="0.6">0.6 miles</option>
  <option value="0.7">0.7 miles</option>
  <option value="0.8">0.8 miles</option>
  <option value="0.9">0.9 miles</option>
  <option value="1">1 mile</option>
  <option value="1.1">1.1 miles</option>
  <option value="1.2">1.2 miles</option>
  <option value="1.3">1.3 miles</option>
  <option value="1.4">1.4 miles</option>
  <option value="1.5">1.5 miles</option>
  <option value="1.6">1.6 miles</option>
  <option value="1.7">1.7 miles</option>
  <option value="1.8">1.8 miles</option>
  <option value="1.9">1.9 miles</option>
  <option value="2">2 miles</option>
</select>

<%= submit_tag("Search") %>
<% end %>



<div >
        <strong class="mode">Mode of Travel: </strong>
        <select id="mode">
                <option value="TRANSIT">Transit</option>
                <option value="WALKING" selected="selected">Walking</option>
                <option value="BICYCLING">Bicycling</option>
                <option value="DRIVING">Driving</option>
        </select>
</div>


<div>
        <label for="from">Start</label><input type="text" id="from" name="from" /><br>

        <label for="to">End</label><input type="text" id="to" name="to" /><br>
        <p><button type="submit" id="update-route">Get me outta here!</button></p>
        <label for="isHeatmap">Heatmap</label><input type="checkbox"
name="isHeatmap" id="isHeatmap" checked="checked"></input>
</div>
</div>


<body onload="initialize()">
    <div id="map_canvas" style="width:100%; height:100%"></div>
  </body>

app/views/crimes/index.html.erb
<h1>Listing crimes</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Block</th>
    <th>Crime type</th>
    <th>Description</th>
    <th>Location type</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crimes.each do |crime| %>
  <tr>
    <td><%= crime.date %></td>
    <td><%= crime.block %></td>
    <td><%= crime.crime_type %></td>
    <td><%= crime.description %></td>
    <td><%= crime.location_type %></td>
    <td><%= crime.latitude %></td>
    <td><%= crime.longitude %></td>
    <td><%= link_to 'Show', crime %></td>
    <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
    <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Crime', new_crime_path %>

<%- unless @lat_lng %>
<script>
  getGeoLocation();
</script>
<%- end %>

app/views/crimes/new.html.erb
<h1>New crime</h1>

<%= render 'form' %>

<%= link_to 'Back', crimes_path %>

app/views/crimes/old_show_threat.html.erb
<h1>Nearby Crime</h1>

<ul> 
<li>lat <%= @lat %></li>
<li>long <%= @long %></li>

<table>
  <tr>
    <th>Date</th>
	<th>Address</th>
    <th>Block</th>
    <th>Crime type</th>
    <th>Description</th>
    <th>Location type</th>
    <!-- <th>Latitude</th> -->
    <!-- <th>Longitude</th> -->
    <th>Proximity (miles)</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>

<% @crimes.each do |crime| %>
  <tr>
    <td><%= crime.date %></td>
	<td><%= crime.address %></td>
    <td><%= crime.block %></td>
    <td><%= crime.crime_type %></td>
    <td><%= crime.description %></td>
    <td><%= crime.location_type %></td>

	<td><%= crime.distance.to_f.round(2) %></td>
    <td><%= link_to 'Show', crime %></td>
    <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
    <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/crimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>Current Location: <%= "#{@lat} and #{@long}" %></p>


<p>
  <b>Date:</b>
  <%= @crime.date %>
</p>

<p>
  <b>Block:</b>
  <%= @crime.block %>
</p>

<p>
  <b>Crime type:</b>
  <%= @crime.crime_type %>
</p>

<p>
  <b>Description:</b>
  <%= @crime.description %>
</p>

<p>
  <b>Location type:</b>
  <%= @crime.location_type %>
</p>

<p>
  <b>Latitude:</b>
  <%= @crime.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @crime.longitude %>
</p>


<%= link_to 'Edit', edit_crime_path(@crime) %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/show_threat.html.erb
<head>
	<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
	
</head>


<h1 class="nearby_crime">Nearby Crime</h1>



<% @crimes.each do |crime| %>
<ul class="crime_event">
	<li class="crime_address"><%= crime.address %></li>
	<li class="crime_type"><span class="name">Crime Type:</span> <span class="value"><%= crime.crime_type %></span></li>
	<li class="crime_description"><span class="name">Description:</span> <span class="value"><%= crime.description %></span></li>
	<li class="location_type"><span class="name">Location Type:</span> <span class="value"><%= crime.location_type %></span></li>
	<li class="date"><%= crime.date %></li>
	<li class="proximity"><%= crime.distance.to_f.round(2) %> mi.</li>
</ul>
<% end %>

app/views/crimes/upload_csv.html.erb
<% form_for :dump, :url=>{:controller=>"crimes", :action=>"csv_import"}, :html => { :multipart => true } do |f| -%>
 <table">
   <tr>
     <td>
      <label for="dump_file">
        Select a CSV File :
      </label>
     </td>
     <td >
       <%= f.file_field :file -%>
     </td>
   </tr>
   <tr>
     <td colspan='2'>
       <%= submit_tag 'Submit' -%>
     </td>
   </tr>
 </table>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrimeApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>